#!/bin/env bash

mkdir -p bot-instance/var/run/tarantool
mkdir -p bot-instance/var/lib/tarantool
mkdir -p bot-instance/var/log/tarantool

chmod -R 777 bot-instance/var/run/tarantool
chmod -R 777 bot-instance/var/log/tarantool
chmod -R 777 bot-instance/var/lib/tarantool

docker run -it --rm \
  -v "$(realpath bot-instance/src)":/usr/local/bot-instance/src:ro \
  -v "$(realpath bot-instance/conf)":/usr/local/bot-instance/conf:ro \
  -v "$(realpath bot-instance/app.lua)":/usr/local/bot-instance/app.lua:ro \
  -v "$(realpath bot-instance/var/lib/tarantool)":/var/lib/tarantool \
  -v "$(realpath bot-instance/var/log/tarantool)":/var/log/tarantool \
  -v "$(realpath bot-instance/var/run/tarantool)":/var/run/tarantool \
    -e BOT_TOKEN="${BOT_TOKEN}" \
  tarantool-run:3.6
